name: build

on:
  pull_request:
    branches:
      - "main"
    paths:
    - '.github/**'
    - '**.go'
    - 'go.mod'
    - 'go.sum'
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Install requirements for raylib-go
      run: sudo apt-get install libgl1-mesa-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libwayland-dev libxkbcommon-dev

    - name: Build windows
      run: go build -o bin/ -ldflags "-H windowsgui -X 'github.com/Appelfeldt/osfmonitor/cmd.BuildVersion=${{ github.ref }}'" -v ./...
      env:
        CGO_ENABLED: 1
        GOOS: windows
        GOARCH: amd64